spring.application.name=deposito_plazo

# Configuración de la conexión a MySQL en Railway
spring.datasource.url=jdbc:mysql://switchback.proxy.rlwy.net:39343/railway
spring.datasource.username=root
spring.datasource.password=ZAxHPzTnOMzFtHnQjNiLxgaTOagCiqIj
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Configuración del servidor
server.port=39343